# Use a Python runtime as a parent image
FROM python:3.7.3-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any necessary dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Start the Celery worker
CMD celery -A run_celery.celery worker --loglevel=info